using System;using System.Collections.Generic;using System.Diagnostics;using System.Drawing;using System.Linq;using System.Runtime.InteropServices;using System.Threading;using System.Windows.Forms;
namespace CyberPW.Assistant2{
internal sealed class BossRecord{public string name{get;set;}public string zone{get;set;}public int x{get;set;}public int y{get;set;}}
internal sealed class BossesPage:UserControl,IModulePage{
 readonly ComboBox games=new ComboBox();readonly Label count,status;readonly TabControl tabs=new TabControl();readonly ListView world=new ListView(),chrono=new ListView();readonly CheckBox opened=new CheckBox();List<BossRecord> bosses;public string Title{get{return"Світові боси";}}
 public BossesPage(){BackColor=Theme.Ink;BackgroundImage=AssetImages.Load("summer","bosses.jpg");BackgroundImageLayout=ImageLayout.Stretch;bosses=JsonFiles.Read<List<BossRecord>>(System.IO.Path.Combine(AppPaths.Data,"bosses.json"));var h=Theme.Label("СВІТОВІ БОСИ",24,Theme.GoldSoft,FontStyle.Bold);h.Location=new Point(24,14);Controls.Add(h);var sub=Theme.Label("Координати, хроно-розклад і встановлення міток у CyberPW",10,Theme.Muted,FontStyle.Regular);sub.Location=new Point(26,50);Controls.Add(sub);var gl=Theme.Label("ВІКНО ГРИ",9,Theme.GoldSoft,FontStyle.Bold);gl.Location=new Point(26,82);Controls.Add(gl);games.SetBounds(26,106,545,30);games.DropDownStyle=ComboBoxStyle.DropDownList;games.BackColor=Theme.Panel;games.ForeColor=Theme.Text;Controls.Add(games);var refresh=Theme.Button("↻ ОНОВИТИ");refresh.SetBounds(585,103,130,36);refresh.Click+=(s,e)=>RefreshGames();Controls.Add(refresh);count=Theme.Label("Вікон: 0",9,Theme.Cyan,FontStyle.Bold);count.Location=new Point(730,110);Controls.Add(count);
 tabs.SetBounds(24,153,870,390);var wp=new TabPage("Світові боси"){BackColor=Theme.Panel};var cp=new TabPage("Хроно-боси"){BackColor=Theme.Panel};var dp=new TabPage("Дроп і розклад"){BackColor=Theme.Panel};Setup(world,bosses.Where(x=>x.zone=="Основний світ"));Setup(chrono,bosses.Where(x=>x.zone!="Основний світ"));world.Dock=chrono.Dock=DockStyle.Fill;wp.Controls.Add(world);cp.Controls.Add(chrono);var drop=new RichTextBox{Dock=DockStyle.Fill,ReadOnly=true,BackColor=Theme.Panel,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Segoe UI",10),Text=DropText};dp.Controls.Add(drop);tabs.TabPages.AddRange(new[]{wp,cp,dp});Controls.Add(tabs);
 opened.Text="Панель координат уже відкрита";opened.SetBounds(28,557,275,28);opened.ForeColor=Theme.Text;opened.BackColor=Color.Transparent;Controls.Add(opened);var open=Theme.Button("ВІДКРИТИ ПАНЕЛЬ КООРДИНАТ");open.SetBounds(28,592,280,42);open.Click+=(s,e)=>OpenPanel();Controls.Add(open);var put=Theme.Button("📍 ПОСТАВИТИ МІТКУ");put.SetBounds(620,582,274,52);put.Click+=(s,e)=>Inject();Controls.Add(put);status=Theme.Label("Використовується калібрування TitulHelper",9,Theme.Cyan,FontStyle.Bold);status.SetBounds(325,596,280,38);Controls.Add(status);world.DoubleClick+=(s,e)=>Inject();chrono.DoubleClick+=(s,e)=>Inject();RefreshGames();}
 static string DropText="З усіх хроно-босів випадають однакові предмети:\n\nКамінь безсмертних, коробка 10 шт. — 16%\nСкарб минулого — 12%\nЗолоте яйце — 10%\nБіла, зелена, чорна, червона та жовта яшма 10 рівня — по 6%\nРубіновий, сапфіровий, смарагдовий, бурштиновий і топазовий камінь 10 рівня — по 4,5%\nКамені сліпучого світла, безмежності та морської лазурі — по 2,5%\nЧервоне око — 2%\n\nЧас появи:\nВівторок — 18:00\nЧетвер — 21:00\nНеділя — 15:00";
 void Setup(ListView l,IEnumerable<BossRecord> data){l.View=View.Details;l.FullRowSelect=true;l.GridLines=true;l.BackColor=Theme.Panel;l.ForeColor=Theme.Text;l.Columns.Add("Бос",430);l.Columns.Add("Локація",145);l.Columns.Add("Координати",120);foreach(var b in data){var r=new ListViewItem(b.name);r.SubItems.Add(b.zone);r.SubItems.Add(b.x+" "+b.y);r.Tag=b;l.Items.Add(r);}}
 void RefreshGames(){int old=games.SelectedItem is GameItem?(games.SelectedItem as GameItem).Id:0;games.Items.Clear();foreach(var p in Process.GetProcessesByName("ElementClient").Where(x=>x.MainWindowHandle!=IntPtr.Zero).OrderBy(x=>x.Id))games.Items.Add(new GameItem(p));for(int i=0;i<games.Items.Count;i++)if(((GameItem)games.Items[i]).Id==old)games.SelectedIndex=i;if(games.SelectedIndex<0&&games.Items.Count>0)games.SelectedIndex=0;count.Text="Вікон: "+games.Items.Count;}
 BossRecord Selected(){ListView l=tabs.SelectedIndex==0?world:tabs.SelectedIndex==1?chrono:null;return l!=null&&l.SelectedItems.Count==1?(BossRecord)l.SelectedItems[0].Tag:null;}Process Game(){var x=games.SelectedItem as GameItem;return x==null?null:Process.GetProcessById(x.Id);}Dictionary<string,object> Config(){return JsonFiles.Read<TitleState>(System.IO.Path.Combine(AppPaths.Data,"state.json")).config;}
 int C(Dictionary<string,object>d,string k,int v){object x;int n;return d.TryGetValue(k,out x)&&int.TryParse(Convert.ToString(x),out n)?n:v;}void ClickAt(Process p,int x,int y){RECT r;if(!GetWindowRect(p.MainWindowHandle,out r))throw new InvalidOperationException("Не вдалося визначити вікно гри.");SetCursorPos(r.L+x,r.T+y);mouse_event(2,0,0,0,UIntPtr.Zero);mouse_event(4,0,0,0,UIntPtr.Zero);}void Focus(Process p){ShowWindowAsync(p.MainWindowHandle,9);SetForegroundWindow(p.MainWindowHandle);Thread.Sleep(300);}
 void OpenPanel(){try{var p=Game();if(p==null)throw new InvalidOperationException("Виберіть вікно гри.");var c=Config();if(C(c,"OpenOffsetX",0)<=0)throw new InvalidOperationException("Спочатку налаштуйте кнопку координат у TitulHelper.");Focus(p);ClickAt(p,C(c,"OpenOffsetX",0),C(c,"OpenOffsetY",0));Thread.Sleep(C(c,"DelayMs",650));opened.Checked=true;status.Text="ПАНЕЛЬ ВІДКРИТО";}catch(Exception e){MessageBox.Show(e.Message,"Світові боси");}}
 void Inject(){try{var b=Selected();if(b==null)throw new InvalidOperationException("Виберіть боса у списку.");var p=Game();if(p==null)throw new InvalidOperationException("Виберіть вікно гри.");var c=Config();if(C(c,"OpenOffsetX",0)<=0||C(c,"CoordOffsetX",0)<=0)throw new InvalidOperationException("Спочатку виконайте обидва кроки налаштування координат у TitulHelper.");Focus(p);if(!opened.Checked){ClickAt(p,C(c,"OpenOffsetX",0),C(c,"OpenOffsetY",0));Thread.Sleep(C(c,"DelayMs",650));opened.Checked=true;}ClickAt(p,C(c,"CoordOffsetX",0),C(c,"CoordOffsetY",0));Thread.Sleep(180);SendKeys.SendWait("{END}");SendKeys.SendWait("{BACKSPACE 12}");SendKeys.SendWait(b.x+" "+b.y);SendKeys.SendWait("{ENTER}");Thread.Sleep(C(c,"DelayMs",650));SendKeys.SendWait(b.name);SendKeys.SendWait("{ENTER}");status.Text="МІТКУ ВСТАНОВЛЕНО: "+b.name;}catch(Exception e){MessageBox.Show(e.Message,"Світові боси");}}
 public void OnActivated(){RefreshGames();}[DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr h);[DllImport("user32.dll")]static extern bool ShowWindowAsync(IntPtr h,int c);[DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);[DllImport("user32.dll")]static extern void mouse_event(uint f,uint x,uint y,int d,UIntPtr e);[DllImport("user32.dll")]static extern bool GetWindowRect(IntPtr h,out RECT r);struct RECT{public int L,T,R,B;}
}
internal sealed class GameItem{public int Id;string text;public GameItem(Process p){Id=p.Id;text=(string.IsNullOrWhiteSpace(p.MainWindowTitle)?"ElementClient":p.MainWindowTitle)+" · PID "+p.Id;}public override string ToString(){return text;}}
}
