using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Linq;using System.Windows.Forms;
namespace CyberPW.Assistant2{internal sealed class DashboardPage:UserControl,IModulePage{
 sealed class EventRow{public string Time,Name;public EventRow(string t,string n){Time=t;Name=n;}}
 readonly Action<string> nav;readonly Label progress,calendarDay,calendarNext,calendarEvents;readonly Button[] dayButtons=new Button[7];int selectedDay;readonly List<EventRow>[] schedule=BuildSchedule();public string Title{get{return"Головна";}}
 public DashboardPage(Action<string> navigate){nav=navigate;BackColor=Theme.Ink;BackgroundImage=AssetImages.Load("main-summer.jpg");BackgroundImageLayout=ImageLayout.Stretch;var hero=new CardPanel{BackColor=Color.FromArgb(0,54,45),BorderThickness=2};hero.SetBounds(18,18,590,250);Controls.Add(hero);var title=Theme.Label("CyberPW Assistant",27,Theme.GoldSoft,FontStyle.Bold);title.Location=new Point(28,25);hero.Controls.Add(title);var sub=Theme.Label("ІНСТРУМЕНТИ ТА ПОМІЧНИКИ ДЛЯ PERFECT WORLD",10,Theme.Text,FontStyle.Bold);sub.Location=new Point(30,78);hero.Controls.Add(sub);var text=Theme.Label("Шість модулів в одному швидкому лаунчері:\nтитули, персонажі, макроси, симуляція,\nфоновий рендер і світові боси.",11,Theme.Muted,FontStyle.Regular);text.Location=new Point(30,116);hero.Controls.Add(text);progress=Theme.Label("TITULHELPER: 0 / 260    ● ГОТОВО    VERSION 2.0 BETA",9,Theme.Cyan,FontStyle.Bold);progress.Location=new Point(30,205);hero.Controls.Add(progress);
  var calendar=new CardPanel{BackColor=Color.FromArgb(0,48,40),BorderThickness=3};calendar.SetBounds(625,18,385,250);Controls.Add(calendar);var ch=Theme.Label("КАЛЕНДАР ІВЕНТІВ",12,Theme.GoldSoft,FontStyle.Bold);ch.Location=new Point(18,14);calendar.Controls.Add(ch);calendarDay=Theme.Label("",9,Theme.Muted,FontStyle.Bold);calendarDay.AutoSize=false;calendarDay.TextAlign=ContentAlignment.MiddleRight;calendarDay.SetBounds(270,14,95,24);calendar.Controls.Add(calendarDay);calendarNext=Theme.Label("",8.5f,Theme.Cyan,FontStyle.Bold);calendarNext.SetBounds(18,47,347,28);calendarNext.AutoSize=false;calendar.Controls.Add(calendarNext);string[] days={"ПН","ВТ","СР","ЧТ","ПТ","СБ","НД"};for(int i=0;i<7;i++){int index=i;var b=Theme.Button(days[i]);b.SetBounds(18+i*50,82,42,34);b.Click+=(s,e)=>SelectDay(index);dayButtons[i]=b;calendar.Controls.Add(b);}calendarEvents=Theme.Label("",8.5f,Theme.Text,FontStyle.Regular);calendarEvents.SetBounds(20,127,345,108);calendarEvents.AutoSize=false;calendar.Controls.Add(calendarEvents);
  string[,] data={{"TITULHELPER","Титули, синхронізація та мітки","titles.jpg"},{"MULTILAUNCHER","Профілі та запуск клієнтів","multilauncher.jpg"},{"СИМУЛЯТОР","Скриня Тора і статистика дропу","simulator.jpg"},{"МАКРОСИ","Клавіатура, миша та пікселі","macros.jpg"},{"РОЗМОРОЗКА","Фоновий рендер вибраних вікон","unfreeze.jpg"},{"СВІТОВІ БОСИ","Координати, хроно та розклад","bosses.jpg"}};for(int i=0;i<data.GetLength(0);i++){int row=i/4,col=i%4;var card=new CardPanel{BackColor=Theme.Panel,BackgroundImage=AssetImages.Load("summer",data[i,2]),BackgroundImageLayout=ImageLayout.Stretch,BorderThickness=2};card.SetBounds(18+col*250,292+row*150,235,135);string key=data[i,0];var h=Theme.Label(key,10,Theme.GoldSoft,FontStyle.Bold);h.Location=new Point(14,12);card.Controls.Add(h);var d=Theme.Label(data[i,1],8,Theme.Text,FontStyle.Regular);d.SetBounds(14,39,207,36);d.AutoSize=false;card.Controls.Add(d);var open=Theme.Button("ВІДКРИТИ");open.SetBounds(12,88,211,34);open.Click+=(s,e)=>nav(key);card.Controls.Add(open);Controls.Add(card);}selectedDay=DayIndex(DateTime.Now.DayOfWeek);SelectDay(selectedDay);UpdateProgress();}
 void SelectDay(int index){selectedDay=index;for(int i=0;i<dayButtons.Length;i++){dayButtons[i].BackColor=i==index?Color.FromArgb(185,137,10):Theme.Panel2;dayButtons[i].ForeColor=i==index?Color.White:Theme.GoldSoft;}calendarDay.Text=DayName(index);var rows=schedule[index];calendarEvents.Text=string.Join("\n",rows.Select(x=>x.Time.PadRight(15)+x.Name).ToArray());string next=NextText(index,rows);calendarNext.Text=next==null?"НАСТУПНЕ: подій більше немає":"НАСТУПНЕ: "+next;}
 string NextText(int index,List<EventRow> rows){if(rows.Count==0)return null;bool today=index==DayIndex(DateTime.Now.DayOfWeek);TimeSpan now=DateTime.Now.TimeOfDay;foreach(var row in rows){foreach(string token in row.Time.Split('·')){string value=token.Trim();int dash=value.IndexOf('–');if(dash>0)value=value.Substring(0,dash);TimeSpan time;if(TimeSpan.TryParse(value.Replace('.',':'),out time)&&(!today||time>=now))return value+" · "+row.Name;}}return null;} void UpdateProgress(){try{int total=JsonFiles.Read<List<TitleRecord>>(AppPaths.Titles).Count,done=0;if(File.Exists(AppPaths.State)){var s=JsonFiles.Read<TitleState>(AppPaths.State);if(s!=null&&s.done!=null)done=s.done.Count(x=>x.Value);}progress.Text="TITULHELPER: "+done+" / "+total+"    ● ГОТОВО    VERSION 2.0 BETA";}catch{}}
 static int DayIndex(DayOfWeek d){return d==DayOfWeek.Sunday?6:(int)d-1;}static string DayName(int i){return new[]{"Понеділок","Вівторок","Середа","Четвер","Пʼятниця","Субота","Неділя"}[i];}
 static List<EventRow>[] BuildSchedule(){var s=new List<EventRow>[7];for(int i=0;i<7;i++)s[i]=new List<EventRow>();Add(s,0,"12:20 · 21:20","Скачки на острові змій");Add(s,0,"19:00–19:30","Плато Асурів");Add(s,0,"21:00","Атака тигрів небожителів");Add(s,1,"12:20 · 21:20","Скачки на острові змій");Add(s,1,"19:00–19:30","Плато Асурів");Add(s,1,"20:00","Світові боси · Хроно боси");Add(s,1,"20:40","Інгримунд");Add(s,2,"12:20 · 21:20","Скачки на острові змій");Add(s,2,"19:00","Початок ставок");Add(s,2,"21:00","Місто Темних звірів");Add(s,3,"12:20 · 21:20","Скачки на острові змій");Add(s,3,"19:00","Закінчення ставок");Add(s,3,"20:00","Конкурс ремісників · боси");Add(s,3,"21:40","Ейнгард");Add(s,4,"12:20 · 21:20","Скачки на острові змій");Add(s,4,"19:00–19:30","Плато Асурів");Add(s,4,"20:20–21:20","Битва Династій");Add(s,5,"12:20 · 21:20","Скачки на острові змій");Add(s,5,"19:00–21:18","Територіальні війни");Add(s,5,"19:00–22:00","Битва Орденів");Add(s,6,"12:20 · 21:20","Скачки на острові змій");Add(s,6,"18:00–19:18","Територіальні війни");Add(s,6,"20:20–21:20","Битва Династій");Add(s,6,"21:30","Замок Царя Драконів");return s;}static void Add(List<EventRow>[] s,int d,string t,string n){s[d].Add(new EventRow(t,n));}
 public void OnActivated(){UpdateProgress();SelectDay(selectedDay);}
}}
