using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Linq;using System.Windows.Forms;
namespace CyberPW.Assistant2{internal sealed class DashboardPage:UserControl,IModulePage{
 readonly Action<string> nav;readonly Label progress;public string Title{get{return"Головна";}}
 public DashboardPage(Action<string> navigate){nav=navigate;BackColor=Theme.Ink;BackgroundImage=AssetImages.Load("main-summer.jpg");BackgroundImageLayout=ImageLayout.Stretch;var hero=new Panel{BackColor=Color.FromArgb(0,54,45)};hero.SetBounds(18,18,590,250);Controls.Add(hero);var title=Theme.Label("CyberPW Assistant",27,Theme.GoldSoft,FontStyle.Bold);title.Location=new Point(28,25);hero.Controls.Add(title);var sub=Theme.Label("ІНСТРУМЕНТИ ТА ПОМІЧНИКИ ДЛЯ PERFECT WORLD",10,Theme.Text,FontStyle.Bold);sub.Location=new Point(30,78);hero.Controls.Add(sub);var text=Theme.Label("Шість модулів в одному швидкому лаунчері:\nтитули, персонажі, макроси, симуляція,\nфоновий рендер і світові боси.",11,Theme.Muted,FontStyle.Regular);text.Location=new Point(30,116);hero.Controls.Add(text);progress=Theme.Label("TITULHELPER: 0 / 260    ● ГОТОВО    VERSION 2.0 BETA",9,Theme.Cyan,FontStyle.Bold);progress.Location=new Point(30,205);hero.Controls.Add(progress);Theme.Round(hero,14);
  var calendar=new Panel{BackColor=Color.FromArgb(0,48,40)};calendar.SetBounds(625,18,385,250);Controls.Add(calendar);var ch=Theme.Label("КАЛЕНДАР ІВЕНТІВ",12,Theme.GoldSoft,FontStyle.Bold);ch.Location=new Point(18,14);calendar.Controls.Add(ch);var day=Theme.Label(UkrDay(DateTime.Now.DayOfWeek),9,Theme.Muted,FontStyle.Bold);day.Location=new Point(300,17);calendar.Controls.Add(day);var next=Theme.Label("НАСТУПНЕ: перевірте розклад на сьогодні",9,Theme.Cyan,FontStyle.Bold);next.SetBounds(18,48,345,28);next.AutoSize=false;calendar.Controls.Add(next);string[] days={"ПН","ВТ","СР","ЧТ","ПТ","СБ","НД"};for(int i=0;i<7;i++){var b=Theme.Button(days[i]);b.SetBounds(18+i*50,84,42,32);b.Enabled=false;if(i==DayIndex(DateTime.Now.DayOfWeek))b.BackColor=Color.FromArgb(185,137,10);calendar.Controls.Add(b);}var events=Theme.Label(TodayEvents(DateTime.Now.DayOfWeek),9,Theme.Text,FontStyle.Regular);events.SetBounds(20,130,340,100);events.AutoSize=false;calendar.Controls.Add(events);Theme.Round(calendar,14);
  string[,] data={{"TITULHELPER","Титули, синхронізація та мітки","titles.jpg"},{"MULTILAUNCHER","Профілі та запуск клієнтів","multilauncher.jpg"},{"СИМУЛЯТОР","Скриня Тора і статистика дропу","simulator.jpg"},{"МАКРОСИ","Клавіатура, миша та пікселі","macros.jpg"},{"РОЗМОРОЗКА","Фоновий рендер вибраних вікон","unfreeze.jpg"},{"СВІТОВІ БОСИ","Координати, хроно та розклад","bosses.jpg"}};for(int i=0;i<data.GetLength(0);i++){int row=i/4,col=i%4;var card=new Panel{BackColor=Theme.Panel,BackgroundImage=AssetImages.Load("summer",data[i,2]),BackgroundImageLayout=ImageLayout.Stretch};card.SetBounds(18+col*250,292+row*150,235,135);string key=data[i,0];var h=Theme.Label(key,10,Theme.GoldSoft,FontStyle.Bold);h.Location=new Point(14,12);card.Controls.Add(h);var d=Theme.Label(data[i,1],8,Theme.Text,FontStyle.Regular);d.SetBounds(14,39,207,36);d.AutoSize=false;card.Controls.Add(d);var open=Theme.Button("ВІДКРИТИ");open.SetBounds(12,88,211,34);open.Click+=(s,e)=>nav(key);card.Controls.Add(open);Controls.Add(card);Theme.Round(card,12);}UpdateProgress();}
 void UpdateProgress(){try{int total=JsonFiles.Read<List<TitleRecord>>(AppPaths.Titles).Count,done=0;if(File.Exists(AppPaths.State)){var s=JsonFiles.Read<TitleState>(AppPaths.State);if(s!=null&&s.done!=null)done=s.done.Count(x=>x.Value);}progress.Text="TITULHELPER: "+done+" / "+total+"    ● ГОТОВО    VERSION 2.0 BETA";}catch{}}
 static int DayIndex(DayOfWeek d){return d==DayOfWeek.Sunday?6:(int)d-1;}static string UkrDay(DayOfWeek d){string[] a={"Неділя","Понеділок","Вівторок","Середа","Четвер","Пʼятниця","Субота"};return a[(int)d];}static string TodayEvents(DayOfWeek d){switch(d){case DayOfWeek.Tuesday:return"18:00   Хроно-боси\n20:00   Світові боси\n20:40   Інгримунд";case DayOfWeek.Thursday:return"20:00   Світові боси · Хроно-боси\n21:40   Ейнгард";case DayOfWeek.Sunday:return"15:00   Хроно-боси\n20:00   Світові боси";default:return"12:20–21:20   Щоденні івенти\n20:00   Перевірте календар сервера";}}
 public void OnActivated(){UpdateProgress();}
}}
