using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Threading;using System.Windows.Forms;
namespace CyberPW.Assistant2{
internal sealed class MacroStudioPage:UserControl,IModulePage{
 readonly DataGridView g=new DataGridView();readonly TextBox name=new TextBox(),target=new TextBox(),start=new TextBox(),stop=new TextBox();readonly CheckBox focus=new CheckBox();readonly MacroRunner runner=new MacroRunner();readonly System.Windows.Forms.Timer timer=new System.Windows.Forms.Timer();Label status;bool running,sd,xd;Button stopBtn;
 public string Title{get{return"Macro Studio";}}
 public MacroStudioPage(){BackColor=Theme.Ink;BackgroundImage=AssetImages.Load("summer","macros.jpg");BackgroundImageLayout=ImageLayout.Stretch;
  var h=Theme.Label("MACRO STUDIO · 2.0 (BETA)",24,Theme.GoldSoft,FontStyle.Bold);h.Location=new Point(22,12);Controls.Add(h);var sub=Theme.Label("Графічний конструктор · клавіатура, миша, пікселі та умови",10,Theme.Muted,FontStyle.Regular);sub.Location=new Point(24,48);Controls.Add(sub);
  Field(name,24,76,240,"Новий макрос");Field(target,278,76,150,"ElementClient");focus.SetBounds(445,76,270,30);focus.Text="Активувати вікно перед запуском";focus.Checked=true;focus.ForeColor=Theme.Text;focus.BackColor=Color.Transparent;Controls.Add(focus);
  Grid();g.SetBounds(24,118,620,358);Controls.Add(g);var side=new Panel{BackColor=Color.FromArgb(225,Theme.Panel)};side.SetBounds(660,118,255,450);Controls.Add(side);var help=Theme.Label("ЯК ЦЕ ПРАЦЮЄ\n\n1. Додайте дію кнопкою.\n2. Оберіть клавішу.\n3. Редагуйте значення в таблиці.\n4. Стрілками змініть порядок.\n5. Задайте старт і стоп.",9,Theme.Text,FontStyle.Regular);help.SetBounds(14,12,225,145);side.Controls.Add(help);
  SB(side,"НОВИЙ",14,166,70,(s,e)=>New());SB(side,"ВІДКРИТИ",91,166,74,(s,e)=>Open());SB(side,"ЗБЕРЕГТИ",172,166,70,(s,e)=>Save());SB(side,"ПЕРЕВІРИТИ",14,210,228,(s,e)=>Check());
  var sl=Theme.Label("СТАРТ:",9,Theme.Muted,FontStyle.Bold);sl.SetBounds(15,267,60,25);side.Controls.Add(sl);Field(start,77,263,55,"F10",side);SB(side,"▶ ЗАПУСТИТИ",139,259,103,(s,e)=>Run());var xl=Theme.Label("СТОП:",9,Theme.Muted,FontStyle.Bold);xl.SetBounds(15,313,60,25);side.Controls.Add(xl);Field(stop,77,309,55,"F12",side);stopBtn=SB(side,"■ СТОП",139,305,103,(s,e)=>Stop("ЗУПИНЕНО"));stopBtn.BackColor=Color.FromArgb(90,30,28);status=Theme.Label("ГОТОВО",9,Theme.Cyan,FontStyle.Bold);status.SetBounds(15,360,225,70);side.Controls.Add(status);
  int a=490,b=537,c=584;AB("КЛАВІША",24,a,105,(s,e)=>Pick("KEY","Натиснути клавішу"));AB("⇩ ЗАТИСНУТИ",137,a,115,(s,e)=>Pick("KEYDOWN","Затиснути клавішу"));AB("⇧ ВІДПУСТИТИ",260,a,122,(s,e)=>Pick("KEYUP","Відпустити клавішу"));AB("◷ ПАУЗА",390,a,90,(s,e)=>Add("WAIT","250","Пауза, мс"));AB("T ТЕКСТ",488,a,82,(s,e)=>Add("TEXT","Ваш текст","Ввести текст"));AB("КЛІК МИШІ",578,a,104,Mouse);
  AB("⌖ КУРСОР",24,b,105,(s,e)=>Add("MOVE","500 300","Координати курсора"));AB("↻ ПОВТОР",137,b,115,(s,e)=>Add("REPEAT","3","Початок повтору"));AB("↳ КІНЕЦЬ",260,b,122,(s,e)=>Add("END","","Кінець повтору"));AB("▲",390,b,42,(s,e)=>MoveRow(-1));AB("▼",440,b,42,(s,e)=>MoveRow(1));AB("ВИДАЛИТИ",490,b,192,(s,e)=>{if(g.CurrentRow!=null)g.Rows.Remove(g.CurrentRow);});
  AB("◎ ЧЕКАТИ КОЛІР",24,c,145,(s,e)=>Pixel("WAITCOLOR"));AB("IF КОЛІР",177,c,125,(s,e)=>Pixel("IFCOLOR"));AB("IF NOT КОЛІР",310,c,145,(s,e)=>Pixel("IFNOTCOLOR"));AB("КІНЕЦЬ IF",463,c,219,(s,e)=>Add("ENDIF","","Кінець умови"));timer.Interval=35;timer.Tick+=(s,e)=>Poll();timer.Start();Add("KEY","D1","Натиснути клавішу");Add("WAIT","250","Пауза, мс");Add("KEY","D2","Натиснути клавішу");}
 void Grid(){g.AllowUserToAddRows=false;g.RowHeadersVisible=false;g.SelectionMode=DataGridViewSelectionMode.FullRowSelect;g.MultiSelect=false;g.BackgroundColor=Theme.Panel2;g.GridColor=Color.FromArgb(30,86,72);g.EnableHeadersVisualStyles=false;g.ColumnHeadersDefaultCellStyle.BackColor=Theme.Panel;g.ColumnHeadersDefaultCellStyle.ForeColor=Theme.GoldSoft;g.DefaultCellStyle.BackColor=Theme.Panel2;g.DefaultCellStyle.ForeColor=Theme.Text;g.DefaultCellStyle.SelectionBackColor=Color.FromArgb(20,126,99);g.Columns.Add("c","КОМАНДА");g.Columns.Add("a","ЗНАЧЕННЯ");g.Columns.Add("d","ОПИС");g.Columns[0].Width=110;g.Columns[1].Width=185;g.Columns[2].AutoSizeMode=DataGridViewAutoSizeColumnMode.Fill;g.Columns[0].ReadOnly=true;g.Columns[2].ReadOnly=true;}
 void Field(TextBox t,int x,int y,int w,string v,Control p=null){t.SetBounds(x,y,w,28);t.Text=v;t.BackColor=Theme.Panel2;t.ForeColor=Theme.Text;t.TextAlign=(t==start||t==stop)?HorizontalAlignment.Center:HorizontalAlignment.Left;(p??this).Controls.Add(t);}Button SB(Control p,string t,int x,int y,int w,EventHandler e){var q=Theme.Button(t);q.SetBounds(x,y,w,36);q.Click+=e;p.Controls.Add(q);return q;}void AB(string t,int x,int y,int w,EventHandler e){SB(this,t,x,y,w,e).Height=39;}
 void Add(string c,string a,string d){int i=g.Rows.Add(c,a,d);g.ClearSelection();g.Rows[i].Selected=true;g.CurrentCell=g.Rows[i].Cells[1];}List<MacroRow> Rows(){var r=new List<MacroRow>();foreach(DataGridViewRow x in g.Rows)r.Add(new MacroRow{command=""+x.Cells[0].Value,argument=""+x.Cells[1].Value,description=""+x.Cells[2].Value});return r;}
 void Pick(string c,string d){using(var x=new KeyPickerDialog())if(x.ShowDialog(FindForm())==DialogResult.OK)Add(c,x.SelectedKey,d);}void Mouse(object s,EventArgs e){var m=new ContextMenuStrip();foreach(var x in new[]{"LEFT|Ліва кнопка","RIGHT|Права кнопка","MIDDLE|Коліщатко"}){var z=x.Split('|');var i=new ToolStripMenuItem(z[1]);string v=z[0];i.Click+=(a,b)=>Add("CLICK",v,"Клік миші");m.Items.Add(i);}m.Show((Control)s,0,((Control)s).Height);}
 void Pixel(string c){if(MessageBox.Show("Після OK програма сховається. У вас буде 3 секунди, щоб навести курсор.","Захоплення пікселя",MessageBoxButtons.OKCancel)!=DialogResult.OK)return;var f=FindForm();f.Hide();Point p;Color q;try{Thread.Sleep(3000);p=MacroNative.Cursor();q=MacroNative.Pixel(p.X,p.Y);}finally{f.Show();f.Activate();}string h=ColorTranslator.ToHtml(q),a=c=="WAITCOLOR"?string.Format("{0} {1} {2} 10 10000",p.X,p.Y,h):string.Format("{0} {1} {2} 10",p.X,p.Y,h);Add(c,a,c=="WAITCOLOR"?"Чекати появи кольору":c=="IFCOLOR"?"Якщо колір збігається":"Якщо колір НЕ збігається");Status("ЗАХОПЛЕНО: "+p.X+", "+p.Y+" · "+h,Theme.Cyan);}
 void MoveRow(int d){if(g.CurrentRow==null)return;int i=g.CurrentRow.Index,j=i+d;if(j<0||j>=g.Rows.Count)return;object[] v={g.Rows[i].Cells[0].Value,g.Rows[i].Cells[1].Value,g.Rows[i].Cells[2].Value};g.Rows.RemoveAt(i);g.Rows.Insert(j,v);g.Rows[j].Selected=true;}
 Keys Hot(TextBox b,string n){string v=b.Text.Trim().ToUpperInvariant();if(v.Length==1&&char.IsDigit(v[0]))v="D"+v;Keys k;if(!Enum.TryParse(v,true,out k)||k==Keys.None)throw new InvalidOperationException("Невідома клавіша "+n+": "+b.Text);b.Text=v.Length==2&&v[0]=='D'?v.Substring(1):v;return k;}void Hotkeys(){if(Hot(start,"запуску")==Hot(stop,"зупинки"))throw new InvalidOperationException("Старт і стоп мають бути різними.");stopBtn.Text="■ СТОП · "+stop.Text;}
 void Check(){try{Hotkeys();var x=MacroCompiler.Compile(Rows());if(x.Count==0)throw new InvalidOperationException("Додайте дію.");Status("СЦЕНАРІЙ КОРЕКТНИЙ\nКоманд: "+x.Count,Theme.Cyan);}catch(Exception e){Status(e.Message,Color.IndianRed);}}void New(){if(running)return;name.Text="Новий макрос";start.Text="F10";stop.Text="F12";g.Rows.Clear();Status("НОВИЙ СЦЕНАРІЙ",Theme.Cyan);}string HK(TextBox b){string v=b.Text.Trim().ToUpperInvariant();return v.Length==1&&char.IsDigit(v[0])?"D"+v:v;}
 void Save(){try{Hotkeys();MacroCompiler.Compile(Rows());string n=Safe(name.Text);JsonFiles.Write(Path.Combine(AppPaths.Macros,n+".json"),new MacroFile{schemaVersion=4,name=n,targetProcess=target.Text,startHotkey=HK(start),stopHotkey=HK(stop),steps=Rows()});Status("ЗБЕРЕЖЕНО",Theme.Cyan);}catch(Exception e){Status(e.Message,Color.IndianRed);}}void Open(){using(var d=new OpenFileDialog()){d.InitialDirectory=AppPaths.Macros;d.Filter="Macro (*.json)|*.json";if(d.ShowDialog()!=DialogResult.OK)return;try{var f=JsonFiles.Read<MacroFile>(d.FileName);name.Text=f.name;target.Text=f.targetProcess;start.Text=Show(f.startHotkey,"F10");stop.Text=Show(f.stopHotkey,"F12");g.Rows.Clear();foreach(var r in f.steps)Add(r.command,r.argument,r.description);Hotkeys();Status("ВІДКРИТО",Theme.Cyan);}catch(Exception e){Status(e.Message,Color.IndianRed);}}}
 void Run(){if(running)return;try{Hotkeys();var x=MacroCompiler.Compile(Rows());if(x.Count==0)throw new InvalidOperationException("Додайте дію.");running=true;Status("СТАРТ ЧЕРЕЗ 0.5 С",Theme.GoldSoft);new Thread(()=>{try{Thread.Sleep(500);runner.Run(x,target.Text,focus.Checked);BeginInvoke((Action)(()=>Status("ВИКОНАННЯ ЗАВЕРШЕНО",Theme.Cyan)));}catch(Exception e){BeginInvoke((Action)(()=>Status(e.Message,Color.IndianRed)));}finally{running=false;}}){IsBackground=true}.Start();}catch(Exception e){running=false;Status(e.Message,Color.IndianRed);}}void Stop(string s){runner.Stop();running=false;Status(s,Color.IndianRed);}void Poll(){Keys a,b;try{a=Hot(start,"запуску");b=Hot(stop,"зупинки");}catch{return;}bool n=(MacroNative.GetAsyncKeyState((int)a)&0x8000)!=0,x=(MacroNative.GetAsyncKeyState((int)b)&0x8000)!=0;if(n&&!sd&&!running)Run();if(x&&!xd&&running)Stop("АВАРІЙНО ЗУПИНЕНО");sd=n;xd=x;}void Status(string s,Color c){status.Text=s;status.ForeColor=c;}static string Safe(string s){foreach(char c in Path.GetInvalidFileNameChars())s=s.Replace(c,'_');return string.IsNullOrWhiteSpace(s)?"Новий макрос":s.Trim();}static string Show(string s,string d){if(string.IsNullOrWhiteSpace(s))s=d;return s.Length==2&&s[0]=='D'?s.Substring(1):s;}public void OnActivated(){}
}
internal sealed class KeyPickerDialog:Form{public string SelectedKey{get;private set;}public KeyPickerDialog(){Text="Оберіть клавішу";ClientSize=new Size(825,380);StartPosition=FormStartPosition.CenterParent;BackColor=Theme.Ink;BackgroundImage=AssetImages.Load("summer","macros.jpg");BackgroundImageLayout=ImageLayout.Stretch;string[][] rows={new[]{"Escape","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12"},new[]{"D1","D2","D3","D4","D5","D6","D7","D8","D9","D0","Back","Tab"},new[]{"Q","W","E","R","T","Y","U","I","O","P","Return"},new[]{"A","S","D","F","G","H","J","K","L","Space"},new[]{"Z","X","C","V","B","N","M","Left","Up","Down","Right"},new[]{"LControlKey","LShiftKey","LMenu","RMenu","RShiftKey","RControlKey"}};for(int r=0;r<rows.Length;r++){int x=15;foreach(string k in rows[r]){int w=k=="Space"?220:(k.Contains("Control")||k.Contains("Shift")||k=="Back"||k=="Return")?75:55;var b=Theme.Button(Cap(k));b.SetBounds(x,18+r*58,w,44);string v=k;b.Click+=(s,e)=>{SelectedKey=v;DialogResult=DialogResult.OK;Close();};Controls.Add(b);x+=w+6;}}}static string Cap(string k){if(k=="Escape")return"Esc";if(k=="Back")return"⌫";if(k=="Return")return"Enter";if(k=="Space")return"ПРОБІЛ";if(k=="Left")return"←";if(k=="Up")return"↑";if(k=="Down")return"↓";if(k=="Right")return"→";if(k.Contains("Control"))return"Ctrl";if(k.Contains("Shift"))return"Shift";if(k.Contains("Menu"))return"Alt";return k.Length==2&&k[0]=='D'?k.Substring(1):k;}}
}
