using System;using System.Collections.Generic;using System.Diagnostics;using System.Drawing;using System.IO;using System.Windows.Forms;
namespace CyberPW.Assistant2{internal sealed class MainForm:Form{
 readonly Panel nav,content;readonly Label pageTitle;readonly Dictionary<string,Control> pages=new Dictionary<string,Control>();
 public MainForm(){Text="CyberPW Assistant 2.0 (BETA)";StartPosition=FormStartPosition.CenterScreen;MinimumSize=new Size(1024,700);Size=new Size(1280,820);BackColor=Theme.Ink;ForeColor=Theme.Text;Font=new Font("Segoe UI",9);AutoScaleMode=AutoScaleMode.Dpi;Icon=LoadIcon();nav=new GradientPanel{Dock=DockStyle.Left,Width=230,AutoScroll=true};var work=new Panel{Dock=DockStyle.Fill,BackColor=Theme.Ink};var header=new GradientPanel{Dock=DockStyle.Top,Height=62};pageTitle=Theme.Label("ГОЛОВНА",14,Theme.GoldSoft,FontStyle.Bold);pageTitle.Location=new Point(22,19);header.Controls.Add(pageTitle);var footer=BuildFooter();content=new Panel{Dock=DockStyle.Fill,Padding=new Padding(12),BackColor=Theme.Ink};work.Controls.Add(content);work.Controls.Add(footer);work.Controls.Add(header);header.BringToFront();footer.BringToFront();Controls.Add(work);Controls.Add(nav);nav.BringToFront();BuildNav();Register("ГОЛОВНА",new DashboardPage(ShowPage),new Size(930,620));Register("TITULHELPER",new TitlesPage(),new Size(930,650));Register("MULTILAUNCHER",new MultiLauncherPage(),new Size(850,640));Register("МАКРОСИ",new MacroStudioPage(),new Size(930,650));Register("СИМУЛЯТОР",new SimulatorPage(),new Size(900,650));Register("РОЗМОРОЗКА",new UnfreezePage(),new Size(850,620));Register("СВІТОВІ БОСИ",new BossesPage(),new Size(930,660));ShowPage("ГОЛОВНА");}
 Panel BuildFooter(){var p=new GradientPanel{Dock=DockStyle.Bottom,Height=42};string[,] links={{"☕ БАНКА","https://send.monobank.ua/jar/93N5FBB3zX"},{"▶ YOUTUBE","https://www.youtube.com/@Vitalik_Juk"},{"🌐 САЙТ","https://cyberpw.fun/"},{"💬 ФОРУМ","https://forum.cyberpw.fun/"},{"🎁 РЕЄСТРАЦІЯ + БОНУС","https://cabinet.cyberpw.fun/register.php?ref=4550"},{"⚙ GITHUB ПРОЄКТУ","https://github.com/vitalikjukivskiy/titul_helper"}};int x=18;for(int i=0;i<links.GetLength(0);i++){var l=new LinkLabel{Text=links[i,0],AutoSize=true,LinkColor=Theme.GoldSoft,ActiveLinkColor=Theme.Cyan,VisitedLinkColor=Theme.GoldSoft,BackColor=Color.Transparent,Font=new Font("Segoe UI Semibold",8),Cursor=Cursors.Hand,Location=new Point(x,14),Tag=links[i,1]};l.LinkClicked+=(s,e)=>OpenLink((string)((Control)s).Tag);p.Controls.Add(l);x+=l.PreferredWidth+28;}return p;}
 static void OpenLink(string url){try{Process.Start(new ProcessStartInfo(url){UseShellExecute=true});}catch(Exception e){MessageBox.Show("Не вдалося відкрити посилання.\n"+e.Message,"CyberPW Assistant");}}
 Icon LoadIcon(){try{string p=Path.Combine(AppPaths.Root,"cyberpw-logo.ico");return File.Exists(p)?new Icon(p):null;}catch{return null;}}Image LoadLogo(){try{string p=Path.Combine(AppPaths.Root,"cyberpw-logo.png");if(!File.Exists(p))return null;using(var s=Image.FromFile(p))return new Bitmap(s);}catch{return null;}}
 void BuildNav(){var logo=new PictureBox{Image=LoadLogo(),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.Transparent};logo.SetBounds(24,12,182,76);nav.Controls.Add(logo);var brand=Theme.Label("CyberPW Assistant",14,Theme.GoldSoft,FontStyle.Bold);brand.Location=new Point(24,94);nav.Controls.Add(brand);var ver=Theme.Label("2.0 (BETA)",9,Theme.Cyan,FontStyle.Bold);ver.Location=new Point(25,124);nav.Controls.Add(ver);string[,] items={{"ГОЛОВНА","home.jpg"},{"TITULHELPER","titles.jpg"},{"MULTILAUNCHER","multilauncher.jpg"},{"МАКРОСИ","macros.jpg"},{"СИМУЛЯТОР","simulator.jpg"},{"РОЗМОРОЗКА","unfreeze.jpg"},{"СВІТОВІ БОСИ","bosses.jpg"}};int y=160;for(int i=0;i<items.GetLength(0);i++){string key=items[i,0];var b=Theme.Button(key);b.SetBounds(16,y,198,45);b.TextAlign=ContentAlignment.MiddleLeft;b.Image=AssetImages.LoadSized(30,30,"icons",items[i,1]);b.ImageAlign=ContentAlignment.MiddleLeft;b.TextImageRelation=TextImageRelation.ImageBeforeText;b.Padding=new Padding(10,0,4,0);b.FlatAppearance.MouseOverBackColor=Color.FromArgb(25,105,83);b.Click+=(s,e)=>ShowPage(key);nav.Controls.Add(b);Theme.Round(b,10);y+=51;}}
 void Register(string key,Control page,Size canvas){page.Visible=true;page.Dock=DockStyle.None;page.Location=Point.Empty;var host=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Ink,Visible=false,AutoScrollMinSize=canvas};Action layout=()=>{int w=Math.Max(canvas.Width,host.ClientSize.Width),h=Math.Max(canvas.Height,host.ClientSize.Height);page.SetBounds(0,0,w,h);};host.Resize+=(s,e)=>layout();host.Controls.Add(page);pages[key]=host;host.Tag=page;content.Controls.Add(host);layout();}
 void ShowPage(string key){Control host;if(!pages.TryGetValue(key,out host))return;foreach(Control x in pages.Values)x.Visible=false;((Panel)host).AutoScrollPosition=Point.Empty;host.Visible=true;host.BringToFront();pageTitle.Text=key;var m=host.Tag as IModulePage;if(m!=null)m.OnActivated();}
}}
