using System;using System.Collections.Generic;using System.Drawing;using System.Windows.Forms;
namespace CyberPW.Assistant2{internal sealed class ResponsivePageHost:Panel{
 sealed class Metric{public Control C;public Rectangle B;public float Font;public int[] Columns;public int RowHeight,HeaderHeight;}
 readonly Control page;readonly Size design;readonly List<Metric> metrics=new List<Metric>();bool ready;
 public ResponsivePageHost(Control child,Size designSize){page=child;design=designSize;Dock=DockStyle.Fill;BackColor=Theme.Ink;BackgroundImage=AssetImages.Load("main-summer.jpg");BackgroundImageLayout=ImageLayout.Stretch;DoubleBuffered=true;page.Dock=DockStyle.None;page.Location=Point.Empty;page.Size=design;page.Visible=true;Controls.Add(page);page.CreateControl();page.PerformLayout();CaptureMetrics(page);ready=true;Resize+=(s,e)=>ApplyLayout();VisibleChanged+=(s,e)=>{if(Visible)BeginInvoke((Action)ApplyLayout);};}
 void CaptureMetrics(Control parent){foreach(Control c in parent.Controls){c.PerformLayout();var m=new Metric{C=c,B=c.Bounds,Font=c.Font.SizeInPoints};var dg=c as DataGridView;if(dg!=null){m.Columns=new int[dg.Columns.Count];for(int i=0;i<dg.Columns.Count;i++)m.Columns[i]=dg.Columns[i].Width;m.RowHeight=dg.RowTemplate.Height;m.HeaderHeight=dg.ColumnHeadersHeight;}var lv=c as ListView;if(lv!=null){m.Columns=new int[lv.Columns.Count];for(int i=0;i<lv.Columns.Count;i++)m.Columns[i]=lv.Columns[i].Width;}metrics.Add(m);c.Dock=DockStyle.None;c.Anchor=AnchorStyles.Top|AnchorStyles.Left;CaptureMetrics(c);}}
 public void ApplyLayout(){if(!ready||ClientSize.Width<10||ClientSize.Height<10)return;float sx=(float)ClientSize.Width/design.Width,sy=(float)ClientSize.Height/design.Height,scale=Math.Min(sx,sy);scale=Math.Max(.55f,Math.Min(1.65f,scale));int w=(int)Math.Round(design.Width*scale),h=(int)Math.Round(design.Height*scale);page.SetBounds(Math.Max(0,(ClientSize.Width-w)/2),Math.Max(0,(ClientSize.Height-h)/2),w,h);SuspendLayout();foreach(var m in metrics){m.C.Bounds=new Rectangle((int)Math.Round(m.B.X*scale),(int)Math.Round(m.B.Y*scale),Math.Max(1,(int)Math.Round(m.B.Width*scale)),Math.Max(1,(int)Math.Round(m.B.Height*scale)));if(m.Font>0)m.C.Font=new Font(m.C.Font.FontFamily,Math.Max(6,m.Font*scale),m.C.Font.Style);var dg=m.C as DataGridView;if(dg!=null&&m.Columns!=null){for(int i=0;i<m.Columns.Length;i++)dg.Columns[i].Width=Math.Max(20,(int)(m.Columns[i]*scale));dg.RowTemplate.Height=Math.Max(18,(int)(m.RowHeight*scale));dg.ColumnHeadersHeight=Math.Max(20,(int)(m.HeaderHeight*scale));}var lv=m.C as ListView;if(lv!=null&&m.Columns!=null)for(int i=0;i<m.Columns.Length;i++)lv.Columns[i].Width=Math.Max(25,(int)(m.Columns[i]*scale));}ResumeLayout(true);}
 public Control Page{get{return page;}}
}}
